feat: added external 3ds support using netcetera
juspay/hyperswitch-client-core pull request #6
Opened 2024-05-14 13:27 UTC by Sanskar2001

Added Redirection less 3DS Auth support using Netcetera

2024-05-24 20:02 UTC, vsrivatsa-juspay commented on src/hooks/LoggerHook.res
> +  | AUTHORISE_CALL_INIT
AUTHORIZE (coz American lmao)

2024-05-28 09:13 UTC, vsrivatsa-juspay commented on src/hooks/LoggerHook.res
> +  | AUTHORIZE_CALL_INIT => " AUTHORIZE_CALL_INIT"
```suggestion
  | AUTHORIZE_CALL_INIT => "AUTHORIZE_CALL_INIT"
```

2024-05-28 09:13 UTC, vsrivatsa-juspay commented on src/hooks/LoggerHook.res
> +  | AUTHORIZE_CALL => " AUTHORIZE_CALL"
```suggestion
  | AUTHORIZE_CALL => "AUTHORIZE_CALL"
```

2024-05-28 09:13 UTC, vsrivatsa-juspay commented on src/hooks/LoggerHook.res
> +  | POLL_STATUS_CALL => " POLL_STATUS_CALL"
```suggestion
  | POLL_STATUS_CALL => "POLL_STATUS_CALL"
```

2024-05-28 09:14 UTC, vsrivatsa-juspay commented on src/hooks/LoggerHook.res
> +  | DISPLAY_THREE_DS_SDK => " DISPLAY_THREE_DS_SDK"
```suggestion
  | DISPLAY_THREE_DS_SDK => "DISPLAY_THREE_DS_SDK"
```

2024-05-28 09:14 UTC, vsrivatsa-juspay commented on src/hooks/LoggerHook.res
> +  | NETCETERA_SDK => " NETCETERA_SDK"
```suggestion
  | NETCETERA_SDK => "NETCETERA_SDK"
```

2024-05-28 09:14 UTC, vsrivatsa-juspay requested changes
Whitespaces to be removed in event names

2024-05-29 07:29 UTC, vsrivatsa-juspay commented on src/hooks/NetceteraThreeDsHooks.res
> +      ->Promise.then(res => {
add catch block for the promise

2024-05-29 07:29 UTC, vsrivatsa-juspay commented on src/hooks/NetceteraThreeDsHooks.res
> +        ->Promise.then(data => {
add catch block for the promise

2024-05-29 07:29 UTC, vsrivatsa-juspay commented on src/hooks/NetceteraThreeDsHooks.res
> +      )->Promise.then(data => {
add catch block for the promise

2024-05-29 07:29 UTC, vsrivatsa-juspay commented on src/hooks/NetceteraThreeDsHooks.res
> +      ->Promise.then(data => {
add catch block for the promise

2024-05-29 07:29 UTC, vsrivatsa-juspay commented on src/hooks/NetceteraThreeDsHooks.res
> +              logger(
move this log outside the switch case. We would want to see the value even if its not "C"

2024-05-29 07:29 UTC, vsrivatsa-juspay commented on src/types/ExternalThreeDsTypes.res
> +        threeDSRequestorURL: "https://example.com/3ds-requestor-url",
why is this hardcoded?

2024-05-29 13:10 UTC, vsrivatsa-juspay commented on src/utility/constants/SdkStatusMessages.res
> +let authoriseCallStatus = {
```suggestion
let authorizeCallStatus = {
```

2024-05-29 13:11 UTC, vsrivatsa-juspay commented on src/utility/constants/SdkStatusMessages.res
> +  errorMsg: "authorise failed",
```suggestion
  errorMsg: "authorize failed",
```

2024-05-29 13:11 UTC, vsrivatsa-juspay commented on src/utility/constants/SdkStatusMessages.res
> +  apiCallFailure: "authorise failure, cannot process this payment",
```suggestion
  apiCallFailure: "authorize failure, cannot process this payment",
```

2024-05-31 09:38 UTC, vsrivatsa-juspay submitted a review, later dismissed

2024-05-31 10:14 UTC, vsrivatsa-juspay commented on src/hooks/NetceteraThreeDsHooks.res
> +            status->isStatusSuccess
if else condition

2024-05-31 10:15 UTC, vsrivatsa-juspay commented on src/hooks/NetceteraThreeDsHooks.res
> +            | "processing" => onSuccess(retrievePaymentStatus.successMsg)
```suggestion
            | "processing"
```

2024-05-31 10:16 UTC, vsrivatsa-juspay commented on src/utility/constants/SdkStatusMessages.res
> +  successMsg: "payment authorised successfully",
```suggestion
  successMsg: "payment authorized successfully",
```

2024-07-04 13:02 UTC, aashu331998 approved these changes

2024-07-04 13:02 UTC, merged